# --- HSD specific parameters ---

# use epsilon greedy action selector
action_selector: "soft_epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000       # 500k for 3s5z_vs_3s6z, 6h_vs_8z, otherwise 50k

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

mac: "hsd_mac"
high_agent: "rnn"
low_agent: "hsd_agent"

# 5, 5
n_skills: 8
skill_interval: 10

intrinsic_alpha: 0.6

# use the Q_Learner to train
agent_output_type: "q"
learner: "hsd_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

var_floor: 0.002

save_model: False

# For mpe, we set standarise_rewards True
standardise_rewards: False

name: "hsd_1"